# Use an official Python runtime as a parent image
FROM python:3.11.1

# Set the working directory to /workspace
WORKDIR /workspace

# Install any needed packages specified in requirements.txt
COPY requirements.txt /workspace/
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# You can add any other necessary configurations for your development environment
# Set the working directory to /app
WORKDIR /app